version: '3.8'

services:
  pg-e2e:
    extends:
      file: docker-compose-base.yml
      service: pg
    container_name: pg-e2e
    environment:
      - POSTGRES_DB=nab_test_e2e
    networks:
      - nab-e2e
  pgadmin-e2e:
    extends:
      file: docker-compose-base.yml
      service: pgadmin
    container_name: pgadmin-e2e
    depends_on:
      - pg-e2e
    networks:
      - nab-e2e
    ports:
      - 13591:80
    volumes:
      - "./servers-e2e.json:/pgadmin4/servers.json"
  db:
    extends:
      file: docker-compose-base.yml
      service: db
    container_name: db-e2e
    depends_on:
      - pg-e2e
    environment:
      - DATABASE_HOST=pg-e2e
      - DATABASE_NAME=nab_test_e2e
    networks:
      - nab-e2e
    command: sh -c "node clear && node seed"
  auth:
    extends:
      file: docker-compose-base.yml
      service: auth
    container_name: auth-e2e
    networks:
      - nab-e2e
  log:
    extends:
      file: docker-compose-base.yml
      service: log
    container_name: log-e2e
    depends_on:
      - pg-e2e
    environment:
      - DATABASE_HOST=pg-e2e
      - DATABASE_NAME=nab_test_e2e
    networks:
      - nab-e2e
  order:
    extends:
      file: docker-compose-base.yml
      service: order
    container_name: order-e2e
    depends_on:
      - pg-e2e
      - log
    environment:
      - DATABASE_HOST=pg-e2e
      - DATABASE_NAME=nab_test_e2e
      - LOG_SERVICE_HOST=log
    networks:
      - nab-e2e
  product:
    extends:
      file: docker-compose-base.yml
      service: product
    container_name: product-e2e
    depends_on:
      - pg-e2e
      - log
    environment:
      - DATABASE_HOST=pg-e2e
      - DATABASE_NAME=nab_test_e2e
      - LOG_SERVICE_HOST=log
    networks:
      - nab-e2e
  backend:
    extends:
      file: docker-compose-base.yml
      service: backend
    container_name: backend-e2e
    depends_on:
      - log
      - auth
      - order
      - product
      - pg-e2e
    environment:
      - AUTH_SERVICE_HOST=auth
      - PRODUCT_SERVICE_HOST=product
      - ORDER_SERVICE_HOST=order
      - LOG_SERVICE_HOST=log
    networks:
      - nab-e2e
    working_dir: /app
    command: sh -c "npm run test:e2e -- --reporter mochawesome"
    volumes:
      - ./e2e-report:/app/mochawesome-report
networks:
  nab-e2e:
    name: nab-network
    ipam:
      config:
        - subnet: 10.10.0.0/24
