version: '3.8'

services:
  pg:
    extends:
      file: docker-compose-base.yml
      service: pg
    container_name: pg
    networks:
      - nab
  pgadmin:
    extends:
      file: docker-compose-base.yml
      service: pgadmin
    container_name: pgadmin
    depends_on:
      - pg
    networks:
      - nab
    ports:
      - 13590:80
    volumes:
      - "./servers.json:/pgadmin4/servers.json"
  db:
    extends:
      file: docker-compose-base.yml
      service: db
    depends_on:
      - pg
    networks:
      - nab
    command: sh -c "node seed"
  auth:
    extends:
      file: docker-compose-base.yml
      service: auth
    networks:
      - nab
  log:
    extends:
      file: docker-compose-base.yml
      service: log
    depends_on:
      - pg
    networks:
      - nab
  order:
    extends:
      file: docker-compose-base.yml
      service: order
    depends_on:
      - pg
      - log
      - auth
    networks:
      - nab
  product:
    extends:
      file: docker-compose-base.yml
      service: product
    depends_on:
      - pg
      - log
    networks:
      - nab
  backend:
    extends:
      file: docker-compose-base.yml
      service: backend
    depends_on:
      - order
      - product
    networks:
      - nab
    ports:
      - 80:3000
networks:
  nab:
    name: nab-network
    ipam:
      config:
        - subnet: 10.10.0.0/24
