version: '3.8'

services:
  pg:
    extends:
      file: docker-compose-base.yml
      service: pg
    container_name: pg
    networks:
      - nab
  auth-scale:
    extends:
      file: docker-compose-base.yml
      service: auth
    networks:
      - nab
  log-scale:
    extends:
      file: docker-compose-base.yml
      service: log
    depends_on:
      - pg
    networks:
      - nab
  order-scale:
    extends:
      file: docker-compose-base.yml
      service: order
    depends_on:
      - pg
      - log-scale
      - auth-scale
    networks:
      - nab
  product-scale:
    extends:
      file: docker-compose-base.yml
      service: product
    depends_on:
      - pg
      - log-scale
    networks:
      - nab
  backend-scale:
    extends:
      file: docker-compose-base.yml
      service: backend
    depends_on:
      - order-scale
      - product-scale
    expose:
      - "3000"
    networks:
      - nab
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - backend-scale
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 3001:3000
    networks:
      - nab
networks:
  nab:
    name: nab-network
    ipam:
      config:
        - subnet: 10.10.0.0/24
